MOVIENJOY/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", views.index, name='index'),
    path("account/", include('account.urls')),
    path("logout/", views.user_logout, name='logout'),
    path('admin/', admin.site.urls),
    path("movie/", include('movie.urls')),
    path("review/", include('review.urls')),
    path('about_us/', views.about_us, name="about_us"),
]


urlpatterns += static(settings.MEDIA_DIR, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('profile/',views.profile,name='profile'),
    path('update_profile/',views.update_profile,name='update_profile'),

]

movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('',views.MovieListView.as_view(),name='list'),
    path('<int:pk>/',views.MovieDetailView.as_view(),name='detail'),
]

review/urls.py
from django.urls import path, include
from review import views

app_name = 'review'

urlpatterns = [
    path('',views.ReviewListView.as_view(),name='list'),
    path('<int:pk>/',views.ReviewDetailView.as_view(),name='detail'),
    path('create_review/', views.create_review, name='create_review'),


]

templates/about_us.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
    <h1>About Us</h1>
</div>
<p></p>
<div class="jumbotron">
    <p>As a movie fan, do you often browse the latest movie list but find out there is nothing that really interests
        you? Do
        you want to share your own feelings with everyone other than just friends? Would you like to meet those who have
        similar
        tastes with you?</p> <br>

    <p>In the era of entertainment, there are more and more movies coming out every minute, while its harder and harder
        for us
        to make personalized choices. The media has made blockbusters everywhere for young and old, women and men, but
        it is not
        aware of what is suitable for a group of people just like you. No matter how fair and diligent the expert review
        writers
        are, their help cannot be effective for everyone. A recommendation from like-minded friends not only convey
        their true
        feelings, but also include judgments out of their tastes. Unfortunately, even you try to get suggestions from
        all of
        your friends and family, what they have seen are still limited, and the people with the most similar tastes are
        often
        strangers.</p> <br>

    <p>We, founders of MoviEnjoy, want to provide a platform for you to filter the other “YOU” from thousands of people
        and
        share your opinions with “YOU”. We are not aimed at a certain group of audience and strive to be inclusive. No
        matter
        who you are and what you like, we are glad to help you to get to know confidants and find more interesting
        movies
        through them.</p>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MoviEnJoy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <!-- <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- <div class="navbar-nav"> -->
        <div class="navbar-nav align-items-center">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">MoviEnjoy</a>
            </div>
            <a class="nav-item nav-link" href="{% url 'movie:list' %}">Movies</a>
            <a class="nav-item nav-link" href="{% url 'review:list' %}">Reviews</a>
            <a class="nav-item nav-link" href="{% url 'about_us' %}">About Us</a>
        </div>

        <!-- TODO: search -->
        <nav class="navbar navbar-light bg-light">
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>


        <div class="navbar-nav align-items-center ml-auto">
            {% if user.is_authenticated %}

            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
            <a class="nav-item nav-link" href="{% url 'review:create_review' %}">Create Reviews</a>

            {% else %}
            <a class="nav-item nav-link" href="{% url 'account:register' %}">Register</a>
            <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
            {% endif %}
        </div>
    </nav>


    <div class="container">
        {% block body_block %}
        <!-- anything outside will be inherited -->
        {% endblock %}
    </div>
</body>

</html>

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
    <h1>MoviEnJoy!</h1>
    <h2>Let us hear your juicy voice in the movie world!</h2>
</div>

<!-- TODO: Movie Recommandation system -->
{% endblock %}